version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - app-network
  mongo:
    image: mongo:latest
    ports:
      - '27017'
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
volumes:
  mongodata:
networks:
  app-network:
    driver: bridge 
